---
- hosts: localhost

  tasks:

  - tags: [apt]
    block:
    - apt: update_cache=yes
    - apt: name={{ item }}
      with_items:
        - vim
        - git
        - docker.io
        - openjdk-8-jdk
        - maven
        - python-setuptools
        - python-pip

  - tags: [compose]
    block:
    - pip: name=docker-compose

  - tags: [atom]
    block:
    - get_url: url=https://atom.io/download/deb dest=/tmp/atom.deb
    - apt: deb=/tmp/atom.deb

  - tags: [slack]
    block:
    - get_url: url=https://downloads.slack-edge.com/linux_releases/slack-desktop-2.0.3-amd64.deb dest=/tmp/slack.deb
    - apt: deb=/tmp/slack.deb

  - tags: [chrome]
    block:
    - apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub
    - apt_repository: repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    - apt: name=google-chrome-stable update_cache=yes

  - tags: [sbt]
    block:
    - apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=642AC823
    - apt_repository: repo='deb https://dl.bintray.com/sbt/debian /'
    - apt: name=sbt update_cache=yes

  - tags: [amm]
    block:
    - get_url:  url=https://git.io/vafIQ dest=/usr/local/bin/amm
    - file: path=/usr/local/bin/amm mode=u+x,g+x,o+x

  - tags: [intellij]
    block:
    - unarchive: src=https://download.jetbrains.com/idea/ideaIC-2016.1.tar.gz dest=/var/lib/ copy=no creates=/var/lib/idea-IC-145.258.11/

  - tags: [fish]
    block:
    - apt_repository: repo=ppa:fish-shell/release-2
    - apt: name=fish update_cache=yes
    - user: name=tobias shell=/usr/bin/fish

  - tags: [hub]
    block:
    - unarchive: src=https://github.com/github/hub/releases/download/v2.2.3/hub-linux-amd64-2.2.3.tgz dest=/tmp copy=no creates=/tmp/hub-linux-amd64-2.2.3
    - command: /tmp/hub-linux-amd64-2.2.3/install creates=/usr/local/bin/hub
